spring:
  profiles:
    active: local

---
spring:
  profiles: local

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  datasource:
    url: jdbc:mysql://yjinstance.cvfd8m7cgyo4.ap-northeast-2.rds.amazonaws.com:3306/shortenurl?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 11111111

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

server:
  port: 8080

# Define Your Shorten URL(Domain)
app:
  path:
    local: http://localhost:8080/shorten/